{% set name = "hboard" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DataCanvasIO/HyperBoard/archive/refs/tags/{{ version }}.tar.gz
  sha256: f4d31adca1b9d631eca2e87267277884a5cde81a2b532693bfb4003dea1e0e66

build:
  noarch: python
  number: 0
  script: cd hboard && {{ PYTHON }} -m pip install . -vv
  entry_points:
    - hboard = hboard.cli:main

requirements:
  host:
    - python >=3.6, <3.10
    - pip
  run:
    - python >=3.6, <3.10
    - hypernets >=0.2.5.1, <0.2.6
    - tornado

test:
  imports:
    - hboard
    - hboard.tests
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/DataCanvasIO/HyperBoard
  license: Apache-2.0
  license_file: LICENSE
  summary: Hypernets experiment visualization base on webpage.
  description: |
    This project provides a web based visualization tool for experiment information. In general, Hypernets writes the experiment events into a text file. This tool could monitor the file and make these events visible.
  doc_url: https://hypernets.readthedocs.io
  dev_url: https://github.com/DataCanvasIO/HyperBoard

extra:
  recipe-maintainers:
    - oaksharks
